[package]
name = "hyper-sse"
version = "0.1.0"
authors = ["Klemens Schölhorn <klemens@schoelhorn.eu>"]

[dependencies]
futures = "0.1"
hyper = "0.12"
lazy_static = "1"
serde = "1"
serde_json = "1"
tokio = "0.1"
